package employee.hibernate.entity;

import java.util.Date;

/**
 * Employee generated by hbm2java
 */
public class Employee implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8768611386440414905L;
	
	private Long id;
	private String firstname;
	private String lastname;
	private Date birthDate;
	private String cellPhone;

	public Employee() {
	}

	public Employee(Date birthDate, String cellPhone) {
		this.birthDate = birthDate;
		this.cellPhone = cellPhone;
	}

	public Employee(String firstname, String lastname, Date birthDate, String cellPhone) {
		this.firstname = firstname;
		this.lastname = lastname;
		this.birthDate = birthDate;
		this.cellPhone = cellPhone;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	public Date getBirthDate() {
		return this.birthDate;
	}

	public void setBirthDate(Date birthDate) {
		this.birthDate = birthDate;
	}

	public String getCellPhone() {
		return this.cellPhone;
	}

	public void setCellPhone(String cellPhone) {
		this.cellPhone = cellPhone;
	}

}
